#!/bin/bash

# USAGE:
if [ "$#" != "1" ];
then
    echo "**************************************************************"
    echo "Usage:"
    echo "./sampling_haralick_unormalised_cluster dataPath"
    echo
    echo "Example: ./sampling_haralick_unormalised_cluster ~/Home/Data/"
    echo " "
    echo "Current entry: $0 $*"
    echo "**************************************************************"
    echo " "

    exit
fi

# Affect the input folder for the data
data_path=$1

# Keep the directory of the script into a variable
script_dir=$(pwd)

# Move to the right directory for the processing
cd "/user1/le2i/gu5306le/Work/protoclass/src"

# Create an automatic script
path_haralick='haralick'
path_save='/work/le2i/gu5306le/haralick_unormalised/'
patient_idx=0
script_filename_core='/script_'
script_filename="$script_dir$script_filename_core$patient_idx"
### Create the file
touch $script_filename
### Truncate the file if it is existing
: > $script_filename
### Write the command to execute
printf "ipython protoclass/pipeline/feature-sampling/sampling_haralick_data.py \"${data_path%/}\" \"${path_haralick}\" \"${path_save%/}\"" >> $script_filename
### Make it executable
chmod u+x $script_filename
# Submit the job to the queue
qsub -q batch -pe smp 8 $script_filename
